---
title: Hacking the Library
timezone: America/New_York
collections:
  assignments:
    title: Assignments
    output: true
    permalink: "/assignments/:path/"
  days:
    title: Days
    output: true
    permalink: "/day/:path/"
  pages:
    title: Pages
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: assignments
  values:
    layout: assignment
- scope:
    path: ''
    type: days
  values:
    layout: day
- scope:
    path: ''
    type: pages
  values:
    layout: page
email: steele@osteele.com
description: 'Letâ€™s create a new kind of Library.

'
baseurl: "/"
course:
  title: 'Special Topics in Computing: Hacking the Library'
  number: ENGR3599
gems:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
